name: Web Scraping e Armazenamento

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:  # <- Correção: Movido para dentro do job
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Delete existing data file (if exists)
        run: rm -f dados.txt
      - name: Run script
        run: python seu_script_de_scraping.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualização automática de dados"
          file_pattern: dados.txt
