name: Web Scraping e Armazenamento

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # ou a versão que você precisa
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 # Instale as bibliotecas que você precisa
      - name: Pull latest changes with force (Cuidado!)
        run: git pull --force origin main
      - name: Run script
        run: python seu_script_de_scraping.py
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualização automática de dados"
          file_pattern: dados.txt
