name: Web Scraping e Armazenamento

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4
      - name: Delete existing data file (if any)
        run: rm -f dados.txt

      - name: Run script
        run: python seu_script_de_scraping.py

      - name: Add changed files
        run: git add dados.txt

      - name: Commit changes
        run: git commit -m "Atualização automática de dados" || echo "No changes to commit"

      - name: Pull latest changes before push (Crucial!)
        run: git pull origin main --rebase --strategy recursive --strategy-option ours

      - name: Push changes (force-with-lease para segurança)
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: HEAD:main
          force-with-lease: true
